/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.BorderLayout;
import vista.mru.Distancia;
import vista.mru.Tiempo;
import vista.mru.Velocidad;

/**
 *
 * @author Gutiérrez
 */
public class vistaMRU extends javax.swing.JPanel {

    /**
     * Creates new form vistaMRU
     */
    public vistaMRU() {
        initComponents();
        Velocidad pr = new Velocidad();
        pr.setSize(720, 470);
        pr.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(pr, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        buttonVelocidad = new javax.swing.JButton();
        buttonDistancia = new javax.swing.JButton();
        buttonTiempo = new javax.swing.JButton();
        contenido = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(153, 153, 153));
        bg.setForeground(new java.awt.Color(102, 102, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 235, -1, -1));

        Menu.setBackground(new java.awt.Color(204, 204, 255));

        buttonVelocidad.setText("Velocidad");
        buttonVelocidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVelocidadActionPerformed(evt);
            }
        });

        buttonDistancia.setText("Distancia");
        buttonDistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDistanciaActionPerformed(evt);
            }
        });

        buttonTiempo.setText("Tiempo");
        buttonTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTiempoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(buttonVelocidad)
                .addGap(18, 18, 18)
                .addComponent(buttonDistancia)
                .addGap(18, 18, 18)
                .addComponent(buttonTiempo)
                .addContainerGap(336, Short.MAX_VALUE))
        );

        add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 720, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVelocidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVelocidadActionPerformed
        Velocidad pr = new Velocidad();
        pr.setSize(720, 470);
        pr.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(pr, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_buttonVelocidadActionPerformed

    private void buttonDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDistanciaActionPerformed
        Distancia pr = new Distancia();
        pr.setSize(720, 470);
        pr.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(pr, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_buttonDistanciaActionPerformed

    private void buttonTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTiempoActionPerformed
        Tiempo pr = new Tiempo();
        pr.setSize(720, 470);
        pr.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(pr, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_buttonTiempoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel bg;
    private javax.swing.JButton buttonDistancia;
    private javax.swing.JButton buttonTiempo;
    private javax.swing.JButton buttonVelocidad;
    private javax.swing.JPanel contenido;
    // End of variables declaration//GEN-END:variables
}
